//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreateXmlWebApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DarmanConnection : DbContext
    {
        public DarmanConnection()
            : base("name=DarmanConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Prs_GeneralView> Prs_GeneralView { get; set; }
        public virtual DbSet<HealthVisitView> HealthVisitViews { get; set; }
        public virtual DbSet<HealthContract> HealthContracts { get; set; }
        public virtual DbSet<Prs_Aelemandi> Prs_Aelemandi { get; set; }
        public virtual DbSet<HealthShoParBach> HealthShoParBaches { get; set; }
        public virtual DbSet<HealthRecipeView> HealthRecipeViews { get; set; }
        public virtual DbSet<HealthRecipeKind> HealthRecipeKinds { get; set; }
        public virtual DbSet<HealthRecipeProperty> HealthRecipeProperties { get; set; }
        public virtual DbSet<HealthVisitForWeb> HealthVisitForWebs { get; set; }
        public virtual DbSet<HealthVisit> HealthVisits { get; set; }
        public virtual DbSet<Prs_Personel> Prs_Personel { get; set; }
    }
}
