//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreateXmlWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HealthVisitForWeb
    {
        public Nullable<decimal> Prsnum { get; set; }
        public string Nam { get; set; }
        public string NamKhanevadegi { get; set; }
        public string Mah { get; set; }
        public int MahBachNo { get; set; }
        public decimal RadifVorood { get; set; }
        public string RecipeDesc { get; set; }
        public Nullable<bool> Kardex { get; set; }
        public Nullable<int> ChandNafar { get; set; }
        public string DoctorDesc { get; set; }
        public string RKD { get; set; }
        public string RecipeDate { get; set; }
        public decimal مبلغ_نسخه { get; set; }
        public Nullable<decimal> مبلغ_تایید_شده { get; set; }
        public Nullable<decimal> مبلغ_غیر_تعهد { get; set; }
        public Nullable<decimal> فرانشیز { get; set; }
        public Nullable<decimal> مبلغ_تایید { get; set; }
        public Nullable<decimal> مبلغ_اضافه_شده { get; set; }
        public Nullable<decimal> مبلغ_کسر_شده { get; set; }
        public Nullable<decimal> مبلغ_نهایی { get; set; }
        public string Vazeyat { get; set; }
        public string nesbat { get; set; }
        public string ContractNo { get; set; }
        public string NamVanesbatBimar { get; set; }
        public string NamBimar { get; set; }
        public string NamkhanevadegiBimar { get; set; }
        public decimal VaziatBaste { get; set; }
        public bool TobimeNahaee { get; set; }
        public bool ToBimeAvalie { get; set; }
        public string ShomareParvande { get; set; }
        public string ContractDateAsOf { get; set; }
    }
}
