//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreateXmlWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HealthShoParBach
    {
        public System.Guid ObjectId { get; set; }
        public string Mah { get; set; }
        public int MahBachNo { get; set; }
        public string ShomareParvande { get; set; }
        public bool ToBimeAvalie { get; set; }
        public bool TobimeNahaee { get; set; }
        public decimal VaziatBaste { get; set; }
    }
}
