//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreateXmlWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HealthVisit
    {
        public decimal RadifVorood { get; set; }
        public System.Guid BachId { get; set; }
        public System.Guid ObjectId { get; set; }
        public System.Guid PersonelId { get; set; }
        public System.Guid PatientId { get; set; }
        public System.Guid RecipePropertiesId { get; set; }
        public string RecipeDate { get; set; }
        public string Tarikh { get; set; }
        public decimal RecipeMoney { get; set; }
        public Nullable<decimal> ApprovedDamegMoney { get; set; }
        public Nullable<decimal> OutofContractMoney { get; set; }
        public Nullable<decimal> Franshiz { get; set; }
        public Nullable<decimal> ApprovedMoney { get; set; }
        public Nullable<decimal> AddedMoney { get; set; }
        public Nullable<decimal> DeletedMoney { get; set; }
        public Nullable<decimal> FinalMoney4Pay { get; set; }
        public string PgNumBach { get; set; }
    }
}
