//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreateXmlWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HealthVisitView
    {
        public System.Guid ObjectId { get; set; }
        public Nullable<decimal> Prsnum { get; set; }
        public string Nam { get; set; }
        public string NamKhanevadegi { get; set; }
        public string NamBimar { get; set; }
        public string Nesbat { get; set; }
        public string ShVaziatBaste { get; set; }
        public string TarikhErsalBeBime { get; set; }
        public int ShomareBasteErsalBeBime { get; set; }
        public decimal RadifVorood { get; set; }
        public string Tarikh { get; set; }
        public System.Guid ppppp { get; set; }
        public System.Guid iiiiii { get; set; }
        public string SharhDarman { get; set; }
        public decimal Khesarat { get; set; }
        public Nullable<decimal> Taeed { get; set; }
        public Nullable<decimal> GairTaahod { get; set; }
        public Nullable<decimal> Franshiz { get; set; }
        public Nullable<decimal> Darkhasty { get; set; }
        public Nullable<decimal> AddedMoney { get; set; }
        public Nullable<decimal> DeletedMoney { get; set; }
        public Nullable<decimal> pardakhti { get; set; }
        public Nullable<decimal> Proj_Code { get; set; }
        public string Proj_Name { get; set; }
        public string ContractNo { get; set; }
        public Nullable<int> Radif_Darman { get; set; }
        public string CodeMeli { get; set; }
        public string name { get; set; }
        public string KodMeli { get; set; }
    }
}
