//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreateXmlWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeetingParticipents
    {
        public decimal Prsnum { get; set; }
        public string Nam { get; set; }
        public string NamKhanevadegi { get; set; }
        public string VahedSazmani { get; set; }
        public string Moavenat { get; set; }
        public Nullable<int> Noe_Sherkat { get; set; }
        public Nullable<int> Noe_Eshteghal { get; set; }
    }
}
