//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreateXmlWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prs_GeneralView
    {
        public System.Guid ObjectID { get; set; }
        public Nullable<decimal> Prsnum { get; set; }
        public Nullable<decimal> CardNo { get; set; }
        public string Nam { get; set; }
        public string NamKhanevadegi { get; set; }
        public string TarikhEstekhdam { get; set; }
        public Nullable<int> NoeEstekhdam { get; set; }
        public string ShomareShenasname { get; set; }
        public string NamPedar { get; set; }
        public Nullable<decimal> Hoghogh { get; set; }
        public Nullable<decimal> Sarparasti { get; set; }
        public Nullable<decimal> Mantagheh { get; set; }
        public string TarikhTavalod { get; set; }
        public Nullable<decimal> Jazb { get; set; }
        public Nullable<decimal> SakhtiKar { get; set; }
        public Nullable<decimal> Alemandi { get; set; }
        public Nullable<decimal> Olad { get; set; }
        public Nullable<decimal> TedadFarzandVajedHaghOlad { get; set; }
        public Nullable<decimal> MazayeShoghl { get; set; }
        public Nullable<decimal> SehGaneh { get; set; }
        public Nullable<decimal> TatBigh_Hoghogh { get; set; }
        public Nullable<decimal> TatBigh_Jazb { get; set; }
        public Nullable<decimal> Sayer_Hoghogh { get; set; }
        public Nullable<decimal> FogholAdeMahalKhedmat { get; set; }
        public Nullable<decimal> TatBigh_Hadeaghal_Hoghogh { get; set; }
        public Nullable<decimal> MohitKar { get; set; }
        public Nullable<decimal> Tatbigh3Gane { get; set; }
        public Nullable<decimal> TashilatZendegi { get; set; }
        public Nullable<decimal> HaghMaskan { get; set; }
        public Nullable<decimal> BadiAbVaHava { get; set; }
        public Nullable<decimal> KharoBar { get; set; }
        public Nullable<decimal> FogholadehShoghl { get; set; }
        public Nullable<decimal> SayerMazaya { get; set; }
        public Nullable<int> shift { get; set; }
        public string Khiyabaan { get; set; }
        public string TelPhone { get; set; }
        public string CountryName { get; set; }
        public string CityName { get; set; }
        public string desc_grad { get; set; }
        public string Takhasos { get; set; }
        public string TarikhAkhz { get; set; }
        public string NameDaneshGah { get; set; }
        public string NameReshteh { get; set; }
        public string Gerayeshtahsili { get; set; }
        public string MahalKar { get; set; }
        public string Address { get; set; }
        public string Tarikh_Shoro { get; set; }
        public string Tarikh_Khatemeh { get; set; }
        public string Moddat { get; set; }
        public Nullable<decimal> Proj_Code { get; set; }
        public string Proj_Name { get; set; }
        public string Name { get; set; }
        public string Sharh_Onvan { get; set; }
        public Nullable<decimal> Kod_Onvan { get; set; }
        public string Tarikh_ShoroKarDakhelSherkat { get; set; }
        public string Tarikh_KhatemehKarDakhelSherkat { get; set; }
        public string Modat { get; set; }
        public Nullable<decimal> Emtiaz_Fard { get; set; }
        public Nullable<decimal> Emtiaz_Sholghl { get; set; }
        public Nullable<int> Rotbeh_Shoghl { get; set; }
        public Nullable<int> Rotbeh_Takhsisi { get; set; }
        public Nullable<int> Noe_Eshteghal { get; set; }
        public string Desc_Shift { get; set; }
        public string Desc_Noe_EstekhDam { get; set; }
        public string MAhalTavalod { get; set; }
        public string MahalSodoor { get; set; }
        public string Desc_Jensiat { get; set; }
        public string Moavenat { get; set; }
        public string ShomarehBimeh { get; set; }
        public string NamLatin { get; set; }
        public string NamKhanevadegiLatin { get; set; }
        public string Email { get; set; }
        public Nullable<decimal> ShomareEstekhdam { get; set; }
        public string AddressEzterari { get; set; }
        public string TelephoneEzterari { get; set; }
        public Nullable<int> GorohKhoni { get; set; }
        public Nullable<int> Noe_Sherkat { get; set; }
        public Nullable<int> VaziatTaahol { get; set; }
        public string KodMeli { get; set; }
        public Nullable<int> SaghfSaat { get; set; }
        public Nullable<int> VaziatJesmani { get; set; }
        public Nullable<int> NoeBimeh { get; set; }
        public string NoeNaghseOzv { get; set; }
        public string MahdoodiathaiPezeshki { get; set; }
        public Nullable<decimal> HaghTakhasos { get; set; }
        public Nullable<int> NoeZaban { get; set; }
        public Nullable<int> MizanKhandan { get; set; }
        public Nullable<int> MizanNeveshTan { get; set; }
        public Nullable<int> MizanMokalemeh { get; set; }
        public Nullable<int> Din { get; set; }
        public Nullable<int> Mazhab { get; set; }
        public Nullable<int> VaziatNezamVazifeh { get; set; }
        public string Tabaghe { get; set; }
        public string Cd_section { get; set; }
        public string Section_Cource { get; set; }
        public Nullable<decimal> Work_Num { get; set; }
        public Nullable<short> Code_Grad { get; set; }
        public Nullable<bool> Nezam { get; set; }
        public Nullable<int> TYPE_ONVAN { get; set; }
        public Nullable<int> NoeGhateRabeteh { get; set; }
        public string TarikhGhateRabeteh { get; set; }
        public string ShomarePostSazmani { get; set; }
        public Nullable<int> NumBuild { get; set; }
        public Nullable<int> SaatKarKharej { get; set; }
        public string CodPosty { get; set; }
        public string NamRabet { get; set; }
        public string Mobile { get; set; }
        public string Desc_EllatGhateRabeteh { get; set; }
        public string TozihatHoghogh { get; set; }
        public string MahalAkhzMadrak { get; set; }
        public string Tarikh_Shoroe_Mamoriat { get; set; }
    }
}
