//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreateXmlWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prs_Personel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prs_Personel()
        {
            this.Prs_Aelemandi = new HashSet<Prs_Aelemandi>();
        }
    
        public System.Guid ObjectID { get; set; }
        public Nullable<decimal> ShomareEstekhdam { get; set; }
        public Nullable<decimal> Prsnum { get; set; }
        public Nullable<decimal> CardNo { get; set; }
        public string Nam { get; set; }
        public string NamKhanevadegi { get; set; }
        public string ShomareShenasname { get; set; }
        public string NamPedar { get; set; }
        public string TarikhTavalod { get; set; }
        public Nullable<System.Guid> MahalTavalodID { get; set; }
        public Nullable<System.Guid> MahalSodourID { get; set; }
        public Nullable<int> Jensiat { get; set; }
        public string Tabeiet { get; set; }
        public Nullable<int> VaziatTaahol { get; set; }
        public Nullable<int> Din { get; set; }
        public Nullable<int> Mazhab { get; set; }
        public string KodMeli { get; set; }
        public string ShomarehBimeh { get; set; }
        public Nullable<int> NoeBimeh { get; set; }
        public string NamLatin { get; set; }
        public string NamKhanevadegiLatin { get; set; }
        public Nullable<int> NoeEstekhdam { get; set; }
        public string TarikhEstekhdam { get; set; }
        public Nullable<int> VaziatMaskan { get; set; }
        public string Email { get; set; }
        public string AddressEzterari { get; set; }
        public string TelephoneEzterari { get; set; }
        public string NamRabet { get; set; }
        public Nullable<int> NoeEshteghal { get; set; }
        public Nullable<int> NoeGhateRabeteh { get; set; }
        public string TarikhGhateRabeteh { get; set; }
        public string Mamor { get; set; }
        public string Tarikh_Shoroe_Mamoriat { get; set; }
        public string Tarikh_Khatemeh_Mamoriat { get; set; }
        public string ModatMamoriat { get; set; }
        public Nullable<int> VazeyatPezeshki { get; set; }
        public Nullable<int> GorohKhoni { get; set; }
        public string Mahdodiyet { get; set; }
        public Nullable<decimal> Hoghogh { get; set; }
        public Nullable<decimal> Jazb { get; set; }
        public Nullable<decimal> SakhtiKar { get; set; }
        public Nullable<decimal> Alemandi { get; set; }
        public Nullable<decimal> Olad { get; set; }
        public Nullable<decimal> TedadFarzandVajedHaghOlad { get; set; }
        public Nullable<decimal> MazayeShoghl { get; set; }
        public Nullable<decimal> Sarparasti { get; set; }
        public Nullable<decimal> Mantagheh { get; set; }
        public Nullable<decimal> SehGaneh { get; set; }
        public Nullable<decimal> Takhasos { get; set; }
        public Nullable<decimal> MohitKar { get; set; }
        public Nullable<decimal> TashilatZendegi { get; set; }
        public Nullable<decimal> TatBigh_Hoghogh { get; set; }
        public Nullable<decimal> TatBigh_Jazb { get; set; }
        public Nullable<decimal> TatBigh_Hadeaghal_Hoghogh { get; set; }
        public Nullable<decimal> Tatbigh3Gane { get; set; }
        public Nullable<decimal> Sayer_Hoghogh { get; set; }
        public Nullable<decimal> FogholAdeMahalKhedmat { get; set; }
        public Nullable<decimal> HaghMaskan { get; set; }
        public Nullable<decimal> BadiAbVaHava { get; set; }
        public Nullable<decimal> KharoBar { get; set; }
        public Nullable<decimal> FogholadehShoghl { get; set; }
        public Nullable<decimal> SayerMazaya { get; set; }
        public Nullable<int> VaziatJesmani { get; set; }
        public string NoeNaghseOzv { get; set; }
        public Nullable<int> SaghfSaat { get; set; }
        public string MahdoodiathaiPezeshki { get; set; }
        public Nullable<int> shift { get; set; }
        public Nullable<int> Noe_Sherkat { get; set; }
        public Nullable<int> VaziatNezamVazifeh { get; set; }
        public Nullable<int> NumBuild { get; set; }
        public Nullable<int> SaatKarKharej { get; set; }
        public Nullable<int> EllateGhateRabeteh { get; set; }
        public string TozihatHoghogh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prs_Aelemandi> Prs_Aelemandi { get; set; }
    }
}
