//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreateXmlWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prs_Aelemandi
    {
        public System.Guid ObjectId { get; set; }
        public System.Guid MasterObjectId { get; set; }
        public decimal PrsNum { get; set; }
        public Nullable<int> Radif { get; set; }
        public string Nam { get; set; }
        public string NamKhanevadegi { get; set; }
        public string ShomareShenasNameh { get; set; }
        public string NamPedar { get; set; }
        public Nullable<int> Mazhab { get; set; }
        public Nullable<int> Din { get; set; }
        public Nullable<System.Guid> MahalSodorID { get; set; }
        public Nullable<System.Guid> MahelTavalotID { get; set; }
        public string Tarikh_Tavalot { get; set; }
        public string Tarikh_Azdevaj { get; set; }
        public string Shoghl { get; set; }
        public string MahelKar { get; set; }
        public string AddressMahalKar { get; set; }
        public string Telephone { get; set; }
        public string Tarikh_Talagh { get; set; }
        public string Tarikh_Fot { get; set; }
        public Nullable<int> Nesbat { get; set; }
        public Nullable<bool> Tahttakafol { get; set; }
        public Nullable<bool> BimehShodehYaNashode { get; set; }
        public Nullable<System.Guid> GradID { get; set; }
        public string Tarikh_Bimeh { get; set; }
        public string Tarikh_AraeeMadarek { get; set; }
        public Nullable<int> Radif_Darman { get; set; }
        public string CodeMeli { get; set; }
    
        public virtual Prs_Personel Prs_Personel { get; set; }
    }
}
